grails-app/domain/com/codeharmony/wheeloflife/Rating.groovy
package com.codeharmony.wheeloflife

class Rating {

    Integer value
    boolean isSkip = false
    static belongsTo = [areaOfLife:AreaOfLife, project:Project]

    static constraints = {
        project unique: 'areaOfLife'
        value(inList: 0..10)
    }
}

grails-app/controllers/com/codeharmony/wheeloflife/RatingController.groovy
package com.codeharmony.wheeloflife

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['ROLE_ADMIN'])
class RatingController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Rating.list(params), model: [ratingInstanceCount: Rating.count()]
    }

    def show(Rating ratingInstance) {
        respond ratingInstance
    }

    def create() {
        respond new Rating(params)
    }

    @Transactional
    def save(Rating ratingInstance) {
        if (ratingInstance == null) {
            notFound()
            return
        }

        if (ratingInstance.hasErrors()) {
            respond ratingInstance.errors, view: 'create'
            return
        }

        ratingInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'rating.label', default: 'Rating'), ratingInstance.id])
                redirect ratingInstance
            }
            '*' { respond ratingInstance, [status: CREATED] }
        }
    }

    def edit(Rating ratingInstance) {
        respond ratingInstance
    }

    @Transactional
    def update(Rating ratingInstance) {
        if (ratingInstance == null) {
            notFound()
            return
        }

        if (ratingInstance.hasErrors()) {
            respond ratingInstance.errors, view: 'edit'
            return
        }

        ratingInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Rating.label', default: 'Rating'), ratingInstance.id])
                redirect ratingInstance
            }
            '*' { respond ratingInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Rating ratingInstance) {

        if (ratingInstance == null) {
            notFound()
            return
        }

        ratingInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Rating.label', default: 'Rating'), ratingInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'rating.label', default: 'Rating'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/rating/_form.gsp
<%@ page import="com.codeharmony.wheeloflife.Rating" %>



<div class="fieldcontain ${hasErrors(bean: ratingInstance, field: 'value', 'error')} required">
	<label for="value">
		<g:message code="rating.value.label" default="Value" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="value" from="${ratingInstance.constraints.value.inList}" required="" value="${fieldValue(bean: ratingInstance, field: 'value')}" valueMessagePrefix="rating.value"/>

</div>

<div class="fieldcontain ${hasErrors(bean: ratingInstance, field: 'areaOfLife', 'error')} required">
	<label for="areaOfLife">
		<g:message code="rating.areaOfLife.label" default="Area Of Life" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="areaOfLife" name="areaOfLife.id" from="${com.codeharmony.wheeloflife.AreaOfLife.list()}" optionKey="id" required="" value="${ratingInstance?.areaOfLife?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: ratingInstance, field: 'isSkip', 'error')} ">
	<label for="isSkip">
		<g:message code="rating.isSkip.label" default="Is Skip" />
		
	</label>
	<g:checkBox name="isSkip" value="${ratingInstance?.isSkip}" />

</div>

grails-app/views/rating/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rating.label', default: 'Rating')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-rating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-rating" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${ratingInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${ratingInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:ratingInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/rating/edit.gsp
<%@ page import="com.codeharmony.wheeloflife.Rating" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rating.label', default: 'Rating')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-rating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-rating" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${ratingInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${ratingInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:ratingInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${ratingInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/rating/index.gsp
<%@ page import="com.codeharmony.wheeloflife.Rating" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rating.label', default: 'Rating')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-rating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-rating" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="value" title="${message(code: 'rating.value.label', default: 'Value')}" />
					
						<th><g:message code="rating.areaOfLife.label" default="Area Of Life" /></th>
					
						<g:sortableColumn property="isSkip" title="${message(code: 'rating.isSkip.label', default: 'Is Skip')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${ratingInstanceList}" status="i" var="ratingInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${ratingInstance.id}">${fieldValue(bean: ratingInstance, field: "value")}</g:link></td>
					
						<td>${fieldValue(bean: ratingInstance, field: "areaOfLife")}</td>
					
						<td><g:formatBoolean boolean="${ratingInstance.isSkip}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${ratingInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/rating/show.gsp
<%@ page import="com.codeharmony.wheeloflife.Rating" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rating.label', default: 'Rating')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-rating" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-rating" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list rating">
			
				<g:if test="${ratingInstance?.value}">
				<li class="fieldcontain">
					<span id="value-label" class="property-label"><g:message code="rating.value.label" default="Value" /></span>
					
						<span class="property-value" aria-labelledby="value-label"><g:fieldValue bean="${ratingInstance}" field="value"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${ratingInstance?.areaOfLife}">
				<li class="fieldcontain">
					<span id="areaOfLife-label" class="property-label"><g:message code="rating.areaOfLife.label" default="Area Of Life" /></span>
					
						<span class="property-value" aria-labelledby="areaOfLife-label"><g:link controller="areaOfLife" action="show" id="${ratingInstance?.areaOfLife?.id}">${ratingInstance?.areaOfLife?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${ratingInstance?.isSkip}">
				<li class="fieldcontain">
					<span id="isSkip-label" class="property-label"><g:message code="rating.isSkip.label" default="Is Skip" /></span>
					
						<span class="property-value" aria-labelledby="isSkip-label"><g:formatBoolean boolean="${ratingInstance?.isSkip}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:ratingInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${ratingInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>